[phases.setup]
nixPkgs = ['nodejs-18_x']
cmds = ['npm install -g npm@8']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run preview'

[variables]
NODE_ENV = "production"
NODE_VERSION = "18.x"
NPM_VERSION = "8.x"
