[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
healthcheckProtocol = "http"

[env]
NODE_ENV = "production"
PORT = "8080"
NODE_VERSION = "18.x"
NPM_VERSION = "8.x"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
