[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"
PORT = "3000"
NODE_VERSION = "18.x"
NPM_VERSION = "8.x"
